// <auto-generated />
namespace GoodlyFere.Import.Data.EntityFramework.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ChangePluginDllToAssemblyName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangePluginDllToAssemblyName));
        
        string IMigrationMetadata.Id
        {
            get { return "201302272031499_ChangePluginDllToAssemblyName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
