// <auto-generated />
namespace GoodlyFere.Import.Data.EntityFramework.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddPlugin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPlugin));
        
        string IMigrationMetadata.Id
        {
            get { return "201302260358007_AddPlugin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
